---
- name: Configurar Apache en la maquina target
  hosts: target
  become: true  # para ejecutar con sudo
  tasks:
    - name: Actualizar
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present
    
    - name: Asegurar funcionamiento de apache
      service:
        name: apache2
        state: started
        enabled: yes
          
    - name: Colocar página personalizada
      copy:
        src: files/index.html
        dest: /var/www/html/index.html
